package uva.ipc.practica2.vista;

/**
 * Clase para la interfaz gráfica de la vista de recargar tarjeta
 * @author Fernando Carmona
 * @author Rodrigo Serna
 */
public class VistaRecargarTarjeta extends javax.swing.JFrame {
    private final ControladorRecargarTarjeta miControlador;
    
    /**
     * Crea la nueva vista de recarga de tarjeta
     */
    public VistaRecargarTarjeta() {
        initComponents();
        miControlador = new ControladorRecargarTarjeta(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGlobal = new javax.swing.JPanel();
        pnlCentral = new javax.swing.JPanel();
        pnlBilletes = new javax.swing.JPanel();
        btnBillete10 = new javax.swing.JToggleButton();
        btnBillete20 = new javax.swing.JToggleButton();
        btnBillete50 = new javax.swing.JToggleButton();
        pnlCabecera = new javax.swing.JPanel();
        lbSaldo = new javax.swing.JLabel();
        pnlPie = new javax.swing.JPanel();
        btnRecargar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(233, 255, 255));

        pnlGlobal.setBackground(new java.awt.Color(233, 255, 255));
        pnlGlobal.setLayout(new java.awt.BorderLayout(15, 15));

        pnlCentral.setBackground(new java.awt.Color(233, 255, 255));

        pnlBilletes.setBackground(new java.awt.Color(233, 255, 255));

        btnBillete10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billete10.png"))); // NOI18N
        btnBillete10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillete10ActionPerformed(evt);
            }
        });
        pnlBilletes.add(btnBillete10);

        btnBillete20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billete20.jpg"))); // NOI18N
        btnBillete20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillete20ActionPerformed(evt);
            }
        });
        pnlBilletes.add(btnBillete20);

        btnBillete50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billete50.png"))); // NOI18N
        btnBillete50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillete50ActionPerformed(evt);
            }
        });
        pnlBilletes.add(btnBillete50);

        pnlCentral.add(pnlBilletes);

        pnlGlobal.add(pnlCentral, java.awt.BorderLayout.CENTER);

        pnlCabecera.setBackground(new java.awt.Color(233, 255, 255));

        lbSaldo.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbSaldo.setForeground(new java.awt.Color(94, 145, 136));
        lbSaldo.setText("SALDO DE LA TARJETA: X€");

        javax.swing.GroupLayout pnlCabeceraLayout = new javax.swing.GroupLayout(pnlCabecera);
        pnlCabecera.setLayout(pnlCabeceraLayout);
        pnlCabeceraLayout.setHorizontalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCabeceraLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbSaldo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlCabeceraLayout.setVerticalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCabeceraLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbSaldo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlGlobal.add(pnlCabecera, java.awt.BorderLayout.PAGE_START);

        pnlPie.setBackground(new java.awt.Color(233, 255, 255));
        pnlPie.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        btnRecargar.setBackground(new java.awt.Color(94, 145, 136));
        btnRecargar.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnRecargar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecargar.setText("RECARGAR ESTA CANTIDAD");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        pnlPie.add(btnRecargar);

        btnVolver.setBackground(new java.awt.Color(94, 145, 136));
        btnVolver.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlPie.add(btnVolver);

        pnlGlobal.add(pnlPie, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Eventos-----------------------------------------------------------------------------
    private void btnBillete10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillete10ActionPerformed
        miControlador.procesarBillete10();
    }//GEN-LAST:event_btnBillete10ActionPerformed

    private void btnBillete20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillete20ActionPerformed
        miControlador.procesarBillete20();
    }//GEN-LAST:event_btnBillete20ActionPerformed

    private void btnBillete50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillete50ActionPerformed
        miControlador.procesarBillete50();
    }//GEN-LAST:event_btnBillete50ActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        miControlador.procesarCargarCantidad();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        miControlador.procesarVolver();
    }//GEN-LAST:event_btnVolverActionPerformed

    //Métodos públicos--------------------------------------------------------------------
    public void despulsarBilletes(int uno, int dos, int tres){
        if(uno == 1){
            btnBillete10.setSelected(false);
        }
        
        if(dos == 1){
            btnBillete20.setSelected(false);
        }
        
        if(tres == 1){
            btnBillete50.setSelected(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBillete10;
    private javax.swing.JToggleButton btnBillete20;
    private javax.swing.JToggleButton btnBillete50;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lbSaldo;
    private javax.swing.JPanel pnlBilletes;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlGlobal;
    private javax.swing.JPanel pnlPie;
    // End of variables declaration//GEN-END:variables
}
