package uva.ipc.practica2.vista;

import java.awt.Component;
import java.awt.Container;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import static java.lang.Double.parseDouble;
import java.text.SimpleDateFormat;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.Timer;

/**
 * Clase para la interfaz gráfica de la aplicación
 * @author Fernando Carmona
 * @author Rodrigo Serna
 */
public class VistaComprarBillete extends javax.swing.JFrame {
    private ControladorComprarBilletes miControlador;
    
    /**
     * Cronómetro para comprobar el pago con tarjeta de crédito
     */
    private Timer timer_tarjeta_credito = new Timer(2000, new ActionListener(){
        public void actionPerformed(ActionEvent e){
            miControlador.tarjetaCreditoPasada();
        }
    });
    
    /**
     * Cronómetro para comprobar el pago con la tarjeta de usuario TCyL
     */
    private Timer timer_tarjeta_renfe = new Timer(2000, new ActionListener(){
        public void actionPerformed(ActionEvent e){
            if(miControlador.tarjetaRenfePasada(getPrecio())){
                lb_error4.setVisible(false);
                pago_correcto.setVisible(true);
            }
            else{
                lb_error4.setText("Saldo insuficiente");
                lb_error4.setVisible(true);
            }
        }
    });
    
    /**
     * Crea la vista en el estado inicial (mostrando solo el primer paso)
     */
    public VistaComprarBillete() {
        initComponents();
        miControlador = new Controlador(this);
        cargarEstaciones();
        setVisible(1,0,0);
        setNoVisible(0,1,1);
        pago_correcto.setLocationRelativeTo(null);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pago_correcto = new javax.swing.JDialog();
        lb_pago_aceptado = new javax.swing.JLabel();
        btn_billete = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        info1 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        subtitulo1 = new javax.swing.JLabel();
        btn_sig_p1 = new javax.swing.JButton();
        elegir_salida = new javax.swing.JComboBox<>();
        elegir_destino = new javax.swing.JComboBox<>();
        btn_intercambio = new javax.swing.JButton();
        calendario = new com.toedter.calendar.JDateChooser();
        lb_error1 = new javax.swing.JLabel();
        lb_error2 = new javax.swing.JLabel();
        info2 = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        subtitulo2 = new javax.swing.JLabel();
        btn_sig_p2 = new javax.swing.JButton();
        btn_ant_p2 = new javax.swing.JButton();
        check_box_bici = new javax.swing.JCheckBox();
        check_box_silla = new javax.swing.JCheckBox();
        check_box_mascota = new javax.swing.JCheckBox();
        lb_equipaje = new javax.swing.JLabel();
        lb_bicicleta = new javax.swing.JLabel();
        lb_mascota = new javax.swing.JLabel();
        lb_silla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_rutas_posibles = new javax.swing.JList<>();
        lb_error3 = new javax.swing.JLabel();
        info3 = new javax.swing.JPanel();
        titulo3 = new javax.swing.JLabel();
        subtitulo3 = new javax.swing.JLabel();
        btn_ant_p3 = new javax.swing.JButton();
        radio_btn_credito = new javax.swing.JRadioButton();
        radio_btn_renfe = new javax.swing.JRadioButton();
        lb_tarjetacredito = new javax.swing.JLabel();
        lb_tarjetarenfe = new javax.swing.JLabel();
        lb_mantener_credito = new javax.swing.JLabel();
        pin = new javax.swing.JPasswordField();
        btn_pin = new javax.swing.JButton();
        lb_mantener_renfe = new javax.swing.JLabel();
        lb_pin = new javax.swing.JLabel();
        lb_error4 = new javax.swing.JLabel();

        pago_correcto.setTitle("PAGO CORRECTO");
        pago_correcto.setAlwaysOnTop(true);
        pago_correcto.setBackground(new java.awt.Color(255, 255, 255));
        pago_correcto.setLocation(new java.awt.Point(200, 200));
        pago_correcto.setModal(true);
        pago_correcto.setUndecorated(true);
        pago_correcto.setSize(new java.awt.Dimension(463, 186));

        lb_pago_aceptado.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lb_pago_aceptado.setForeground(new java.awt.Color(0, 153, 0));
        lb_pago_aceptado.setText("EL PAGO HA SIDO PROCESADO CON ÉXITO");

        btn_billete.setText("COMPRAR OTRO BILLETE");
        btn_billete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_billete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_billeteActionPerformed(evt);
            }
        });

        btn_salir.setText("SALIR");
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pago_correctoLayout = new javax.swing.GroupLayout(pago_correcto.getContentPane());
        pago_correcto.getContentPane().setLayout(pago_correctoLayout);
        pago_correctoLayout.setHorizontalGroup(
            pago_correctoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pago_correctoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pago_correctoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pago_correctoLayout.createSequentialGroup()
                        .addComponent(btn_billete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir))
                    .addComponent(lb_pago_aceptado, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pago_correctoLayout.setVerticalGroup(
            pago_correctoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pago_correctoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lb_pago_aceptado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(pago_correctoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_salir)
                    .addComponent(btn_billete))
                .addGap(36, 36, 36))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tren Castilla y León");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setName("app_trenes"); // NOI18N
        setSize(new java.awt.Dimension(1500, 750));
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));

        info1.setBackground(new java.awt.Color(233, 255, 255));
        info1.setPreferredSize(new java.awt.Dimension(500, 750));

        titulo1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        titulo1.setForeground(new java.awt.Color(94, 145, 136));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("PASO 1");
        titulo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        subtitulo1.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        subtitulo1.setForeground(new java.awt.Color(94, 145, 136));
        subtitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo1.setText("ESTACIONES Y FECHAS");
        subtitulo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_sig_p1.setBackground(new java.awt.Color(94, 145, 136));
        btn_sig_p1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btn_sig_p1.setForeground(new java.awt.Color(255, 255, 255));
        btn_sig_p1.setText("SIGUIENTE >");
        btn_sig_p1.setToolTipText("Siguiente paso");
        btn_sig_p1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sig_p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sig_p1ActionPerformed(evt);
            }
        });

        elegir_salida.setBackground(new java.awt.Color(207, 246, 248));
        elegir_salida.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        elegir_salida.setMaximumRowCount(18);
        elegir_salida.setToolTipText("Estación origen");
        elegir_salida.setAutoscrolls(true);
        elegir_salida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elegir_salida.setFocusable(false);
        elegir_salida.setName(""); // NOI18N

        elegir_destino.setBackground(new java.awt.Color(207, 246, 248));
        elegir_destino.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        elegir_destino.setMaximumRowCount(18);
        elegir_destino.setToolTipText("Estación destino");
        elegir_destino.setAutoscrolls(true);
        elegir_destino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elegir_destino.setFocusable(false);

        btn_intercambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechas.png"))); // NOI18N
        btn_intercambio.setToolTipText("Intercambiar origen-destino");
        btn_intercambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_intercambioActionPerformed(evt);
            }
        });

        calendario.setToolTipText("Seleccionar fecha");
        calendario.setDateFormatString("dd-MM-yyyy");
        calendario.setMaxSelectableDate(new java.util.Date(1735603274000L));
        calendario.setMinSelectableDate(new java.util.Date(1704067274000L));

        lb_error1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lb_error1.setForeground(new java.awt.Color(255, 0, 0));
        lb_error1.setText("Ruta no existente");

        lb_error2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lb_error2.setForeground(new java.awt.Color(255, 0, 0));
        lb_error2.setText("Fecha no válida");

        javax.swing.GroupLayout info1Layout = new javax.swing.GroupLayout(info1);
        info1.setLayout(info1Layout);
        info1Layout.setHorizontalGroup(
            info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_sig_p1)
                .addGap(100, 100, 100))
            .addGroup(info1Layout.createSequentialGroup()
                .addGroup(info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(subtitulo1)
                            .addComponent(lb_error1)
                            .addComponent(lb_error2)
                            .addComponent(titulo1)))
                    .addGroup(info1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calendario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, info1Layout.createSequentialGroup()
                                .addGroup(info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(elegir_destino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(elegir_salida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_intercambio)))))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        info1Layout.setVerticalGroup(
            info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitulo1)
                .addGroup(info1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(elegir_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(elegir_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_intercambio)
                        .addGap(61, 61, 61)))
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lb_error1)
                .addGap(18, 18, 18)
                .addComponent(lb_error2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(btn_sig_p1)
                .addGap(75, 75, 75))
        );

        getContentPane().add(info1);

        info2.setBackground(new java.awt.Color(207, 246, 248));
        info2.setPreferredSize(new java.awt.Dimension(500, 750));

        titulo2.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        titulo2.setForeground(new java.awt.Color(94, 145, 136));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("PASO 2");

        subtitulo2.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        subtitulo2.setForeground(new java.awt.Color(94, 145, 136));
        subtitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo2.setText("tREN");
        subtitulo2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        subtitulo2.setMaximumSize(new java.awt.Dimension(268, 19));
        subtitulo2.setMinimumSize(new java.awt.Dimension(268, 19));
        subtitulo2.setPreferredSize(new java.awt.Dimension(268, 19));

        btn_sig_p2.setBackground(new java.awt.Color(94, 145, 136));
        btn_sig_p2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btn_sig_p2.setForeground(new java.awt.Color(255, 255, 255));
        btn_sig_p2.setText("SIGUIENTE >");
        btn_sig_p2.setToolTipText("Siguiente paso");
        btn_sig_p2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sig_p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sig_p2ActionPerformed(evt);
            }
        });

        btn_ant_p2.setBackground(new java.awt.Color(94, 145, 136));
        btn_ant_p2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btn_ant_p2.setForeground(new java.awt.Color(255, 255, 255));
        btn_ant_p2.setText("< ANTERIOR");
        btn_ant_p2.setToolTipText("Anterior paso");
        btn_ant_p2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ant_p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ant_p2ActionPerformed(evt);
            }
        });

        check_box_bici.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        check_box_bici.setForeground(new java.awt.Color(94, 145, 136));
        check_box_bici.setText("Bicicleta");
        check_box_bici.setToolTipText("Marcar si se va a llevar bicicleta");
        check_box_bici.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        check_box_bici.setMaximumSize(new java.awt.Dimension(598, 516));
        check_box_bici.setMinimumSize(new java.awt.Dimension(598, 516));

        check_box_silla.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        check_box_silla.setForeground(new java.awt.Color(94, 145, 136));
        check_box_silla.setText("Silla de ruedas");
        check_box_silla.setToolTipText("Marcar si se va a llevar silla de ruedas");
        check_box_silla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        check_box_mascota.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        check_box_mascota.setForeground(new java.awt.Color(94, 145, 136));
        check_box_mascota.setText("Mascota");
        check_box_mascota.setToolTipText("Marcar si se va a llevar mascota");
        check_box_mascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lb_equipaje.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lb_equipaje.setForeground(new java.awt.Color(94, 145, 136));
        lb_equipaje.setText("Equipaje especial:");

        lb_bicicleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bicicleta.png"))); // NOI18N
        lb_bicicleta.setToolTipText("");

        lb_mascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mascota.png"))); // NOI18N

        lb_silla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/silla.png"))); // NOI18N

        lista_rutas_posibles.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lista_rutas_posibles.setToolTipText("Seleccionar tren");
        lista_rutas_posibles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lista_rutas_posibles.setPreferredSize(new java.awt.Dimension(400, 200));
        jScrollPane1.setViewportView(lista_rutas_posibles);

        lb_error3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lb_error3.setForeground(new java.awt.Color(255, 0, 0));
        lb_error3.setText("Debe seleccionar un billete");

        javax.swing.GroupLayout info2Layout = new javax.swing.GroupLayout(info2);
        info2.setLayout(info2Layout);
        info2Layout.setHorizontalGroup(
            info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info2Layout.createSequentialGroup()
                .addGroup(info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(info2Layout.createSequentialGroup()
                                .addComponent(lb_mascota)
                                .addGap(10, 10, 10)
                                .addGroup(info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(check_box_silla)
                                    .addComponent(check_box_mascota)))
                            .addGroup(info2Layout.createSequentialGroup()
                                .addComponent(lb_bicicleta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(check_box_bici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_silla)
                            .addComponent(lb_equipaje)))
                    .addGroup(info2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(titulo2)
                            .addComponent(subtitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(info2Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lb_error3))
                    .addGroup(info2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(info2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btn_ant_p2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_sig_p2)
                .addGap(100, 100, 100))
        );
        info2Layout.setVerticalGroup(
            info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lb_equipaje)
                .addGap(10, 10, 10)
                .addGroup(info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(check_box_bici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_bicicleta))
                .addGap(0, 0, 0)
                .addGroup(info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(check_box_silla)
                    .addComponent(lb_silla))
                .addGap(0, 0, 0)
                .addGroup(info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(check_box_mascota)
                    .addComponent(lb_mascota))
                .addGap(45, 45, 45)
                .addComponent(lb_error3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(info2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sig_p2)
                    .addComponent(btn_ant_p2))
                .addGap(75, 75, 75))
        );

        getContentPane().add(info2);

        info3.setBackground(new java.awt.Color(181, 236, 242));
        info3.setPreferredSize(new java.awt.Dimension(500, 750));

        titulo3.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        titulo3.setForeground(new java.awt.Color(94, 145, 136));
        titulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo3.setText("PASO 3");

        subtitulo3.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        subtitulo3.setForeground(new java.awt.Color(94, 145, 136));
        subtitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo3.setText("PAGO");
        subtitulo3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_ant_p3.setBackground(new java.awt.Color(94, 145, 136));
        btn_ant_p3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btn_ant_p3.setForeground(new java.awt.Color(255, 255, 255));
        btn_ant_p3.setText("< ANTERIOR");
        btn_ant_p3.setToolTipText("Anterior paso");
        btn_ant_p3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ant_p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ant_p3ActionPerformed(evt);
            }
        });

        radio_btn_credito.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        radio_btn_credito.setForeground(new java.awt.Color(94, 145, 136));
        radio_btn_credito.setText("Tarjeta de crédito");
        radio_btn_credito.setToolTipText("Seleccionar método de pago");
        radio_btn_credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_btn_creditoActionPerformed(evt);
            }
        });

        radio_btn_renfe.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        radio_btn_renfe.setForeground(new java.awt.Color(94, 145, 136));
        radio_btn_renfe.setText("Tarjeta de Usuario TCyL");
        radio_btn_renfe.setToolTipText("Seleccionar método de pago");
        radio_btn_renfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_btn_renfeActionPerformed(evt);
            }
        });

        lb_tarjetacredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tarjeta_credito.jpg"))); // NOI18N
        lb_tarjetacredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_tarjetacreditoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_tarjetacreditoMouseExited(evt);
            }
        });

        lb_tarjetarenfe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tarjeta_renfe.jpg"))); // NOI18N
        lb_tarjetarenfe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_tarjetarenfeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_tarjetarenfeMouseExited(evt);
            }
        });

        lb_mantener_credito.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lb_mantener_credito.setForeground(new java.awt.Color(94, 145, 136));
        lb_mantener_credito.setText("Mantenga la tarjeta AQUÍ 2 segundos");

        pin.setToolTipText("Inserte el PIN");

        btn_pin.setText("ACEPTAR");
        btn_pin.setToolTipText("Aceptar");
        btn_pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pinActionPerformed(evt);
            }
        });

        lb_mantener_renfe.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lb_mantener_renfe.setForeground(new java.awt.Color(94, 145, 136));
        lb_mantener_renfe.setText("Mantenga la tarjeta AQUÍ 2 segundos");

        lb_pin.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lb_pin.setForeground(new java.awt.Color(94, 145, 136));
        lb_pin.setText("PIN:");

        lb_error4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lb_error4.setForeground(new java.awt.Color(255, 0, 0));
        lb_error4.setText("Error al procesar el pago");

        javax.swing.GroupLayout info3Layout = new javax.swing.GroupLayout(info3);
        info3.setLayout(info3Layout);
        info3Layout.setHorizontalGroup(
            info3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(info3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lb_tarjetacredito)
                    .addComponent(lb_mantener_credito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(info3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lb_mantener_renfe)
                    .addComponent(lb_tarjetarenfe))
                .addGap(40, 40, 40))
            .addGroup(info3Layout.createSequentialGroup()
                .addGroup(info3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info3Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(info3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(titulo3)
                            .addComponent(subtitulo3)))
                    .addGroup(info3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lb_pin)
                        .addGap(10, 10, 10)
                        .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btn_pin))
                    .addGroup(info3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btn_ant_p3))
                    .addGroup(info3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(info3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_btn_renfe)
                            .addComponent(radio_btn_credito)))
                    .addGroup(info3Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lb_error4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        info3Layout.setVerticalGroup(
            info3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitulo3)
                .addGap(29, 29, 29)
                .addComponent(radio_btn_credito)
                .addGap(18, 18, 18)
                .addComponent(radio_btn_renfe)
                .addGap(50, 50, 50)
                .addGroup(info3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_tarjetarenfe)
                    .addComponent(lb_tarjetacredito))
                .addGap(10, 10, 10)
                .addGroup(info3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mantener_renfe)
                    .addComponent(lb_mantener_credito))
                .addGap(10, 10, 10)
                .addGroup(info3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lb_pin)
                    .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pin))
                .addGap(38, 38, 38)
                .addComponent(lb_error4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(btn_ant_p3)
                .addGap(75, 75, 75))
        );

        getContentPane().add(info3);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    
    //MÉTODOS PRIVADOS*****************************************************************************************************************
    /**
     * Oculta los pasos indicados como argumentos
     * Se ocultarán aquellos pasos con valor 1 en los parámetros
     * @param uno un número entero que valdrá 1 para ocultar el paso 1
     * @param dos un número entero que valdrá 2 para ocultar el paso 2
     * @param tres un número entero que valdrá 3 para ocultar el paso 3
     */
    private void setNoVisible(int uno, int dos, int tres){        
        Component[] componentesuno;
        Component[] componentesdos;
        Component[] componentestres;
        
        if(uno == 1){
            componentesuno = info1.getComponents();
            for(Component comp : componentesuno){
                    comp.setVisible(false);
            } 
        }
        
        if(dos == 1){
            componentesdos = info2.getComponents();
            for(Component comp : componentesdos){
                    comp.setVisible(false);
            } 
        }
        
        if(tres == 1){
            componentestres = info3.getComponents();
            for(Component comp : componentestres){
                comp.setVisible(false);
            } 
        }   
    }
    
    /**
     * Muestra los pasos indicados como argumentos
     * Se mostrarán aquellos pasos con valor 1 en los parámetros
     * @param uno un número entero que valdrá 1 para mostrar el paso 1
     * @param dos un número entero que valdrá 2 para mostrar el paso 2
     * @param tres un número entero que valdrá 3 para mostrar el paso 3
     */
    private void setVisible(int uno, int dos, int tres){        
        Component[] componentesuno;
        Component[] componentesdos;
        
        if(uno == 1){
            componentesuno = info1.getComponents();
            for(Component comp : componentesuno){
                    comp.setVisible(true);
            }
        }
        
        if(dos == 1){
            componentesdos = info2.getComponents();
            for(Component comp : componentesdos){
                    comp.setVisible(true);
            } 
        }
        
        if(tres == 1){
            titulo3.setVisible(true);
            subtitulo3.setVisible(true);
            btn_ant_p3.setVisible(true);
            radio_btn_renfe.setVisible(true);
            radio_btn_credito.setVisible(true);
        }
        
        resetErrores();
    }
    
    /**
     * Resetea todos los elementos al estado inicial
     */
    private void resetTodo(){
        cargarEstaciones();
        calendario.setDate(null);
        resetErrores();
        lista_rutas_posibles.removeAll();
        check_box_bici.setSelected(false);
        check_box_silla.setSelected(false);
        check_box_mascota.setSelected(false);
        radio_btn_credito.setSelected(false);
        radio_btn_renfe.setSelected(false);
        pin.setText("");
        miControlador.resetTodo();
    }
    
    /**
     * Almacena en los JCombobox de origen y destino las posibles estaciones 
     */
    private void cargarEstaciones(){
        ArrayList<String> aux = new ArrayList<>();
        
        elegir_salida.removeAllItems();
        elegir_destino.removeAllItems();
        aux = miControlador.cargarEstaciones();
        
        for (String item : aux) {
            elegir_salida.addItem(item);
            elegir_destino.addItem(item);
        }   
    }
    
    /**
     * Almacena en el JList de rutas posibles los datos de dichas rutas
     * @param origen la estación de origen
     * @param destino la estación de destino
     * @param findesemana un booleano que indique si la fecha es un fin de semana
     */
    private void cargarRutasPosibles(String origen, String destino, boolean findesemana){
        ArrayList<String> aux = new ArrayList<>();
        
        lista_rutas_posibles.removeAll();
        aux = miControlador.cargarRutasPosibles(getOrigen(), getDestino(), getFinDeSemana());
        String[] add = new String[aux.size()];
        for(int i = 0; i < add.length; i++){
            add[i] = aux.get(i);
        }
        
        lista_rutas_posibles.setListData(add);
    }
    
    /**
     * Elimina la visibilidad de las etiquetas de error
     */
    private void resetErrores(){
        lb_error1.setVisible(false);
        lb_error2.setVisible(false);
        lb_error3.setVisible(false);
        lb_error4.setVisible(false);
    }

    
    
    
    
    
    
    //MÉTODOS PÚBLICOS*****************************************************************************************************************
    /**
     * Consulta la estación de origen
     * @return la estación de origen
     */
    public String getOrigen(){
        return (String)elegir_salida.getSelectedItem();
    }
    
    /**
     * Consulta la estación de destino
     * @return la estación de destino
     */
    public String getDestino(){
        return (String)elegir_destino.getSelectedItem();
    }
    
    /**
     * Consulta la fecha seleccionada por el usuario
     * @return una fecha en formato dd-MM-yyyy
     */
    public String getFecha(){
        SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");  
        
        if(calendario.getDate() != null){
            return formato.format(calendario.getDate());
        }
        
        return null;
    }
    
    /**
     * Consulta si la fecha seleccionada por el usuario cae en fin de semana
     * @return true si es un fin de semana y false en caso contrario
     */
    public boolean getFinDeSemana(){
        Date fecha = calendario.getDate();
        LocalDate localFecha = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        DayOfWeek dia = localFecha.getDayOfWeek();
        
        if(dia == DayOfWeek.SATURDAY || dia == DayOfWeek.SUNDAY){
            return true;
        }
        else{
            return false;
        }
    }
    
    /**
     * Consulta el precio del billete seleccionado por el usuario
     * @return un número mayor o igual a cero
     */
    public double getPrecio(){
        String elem = lista_rutas_posibles.getSelectedValue();
        String[] token = elem.split(" ");
        return parseDouble(token[token.length - 2]);
    }
    
    /**
     * Consulta el PIN introducido por el usuario
     * @return un array de caracteres cualquiera
     */
    public char[] getPIN(){
        return pin.getPassword();
    }
    
    
    
    
    
    
    
    //EVENTOS***************************************************************************************************************************
    
    /**
     * Evento al pulsar el botón de siguiente del primer paso
     */
    private void btn_sig_p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sig_p1ActionPerformed
        if(!miControlador.compEstaciones(getOrigen(), getDestino())){    //Ruta no valida
            lb_error1.setVisible(true);
            lb_error2.setVisible(false);
        }
        else if(!miControlador.compFecha(getFecha())){  //Ruta correcta pero fecha no valida
            lb_error1.setVisible(false);
            lb_error2.setVisible(true);
        }
        else{   //Ambas son correctas
            lb_error1.setVisible(false);
            lb_error2.setVisible(false);
            cargarRutasPosibles(getOrigen(), getDestino(), getFinDeSemana());
                setVisible(0,1,0);       
                setNoVisible(1,0,1);
        }
    }//GEN-LAST:event_btn_sig_p1ActionPerformed

    /**
     * Evento al pulsar el botón de siguiente del segundo paso
     */
    private void btn_sig_p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sig_p2ActionPerformed
        if(!lista_rutas_posibles.isSelectionEmpty()){   //Hay algún elemento seleccionado
            radio_btn_credito.setSelected(false);
            radio_btn_renfe.setSelected(false);
            setVisible(0,0,1);
            setNoVisible(1,1,0);
        }
        else{   //No hay elementos seleccionados
            lb_error3.setVisible(true);
        }
    }//GEN-LAST:event_btn_sig_p2ActionPerformed
    
    /**
     * Evento al pulsar el botón de anterior del segundo paso
     */
    private void btn_ant_p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ant_p2ActionPerformed
        setVisible(1,0,0);
        setNoVisible(0,1,1);
    }//GEN-LAST:event_btn_ant_p2ActionPerformed

    /**
     * Evento al seleccionar la opción de pago con tarjeta de usuario TCyL
     */
    private void radio_btn_renfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_btn_renfeActionPerformed
        miControlador.resetTodo();    
        lb_error4.setVisible(false);
        if(radio_btn_credito.isSelected()){
            radio_btn_credito.setSelected(false);
        }
        radio_btn_renfe.setSelected(true);
        lb_tarjetarenfe.setVisible(true);
        lb_mantener_renfe.setVisible(true);
        lb_tarjetacredito.setVisible(false);
        lb_mantener_credito.setVisible(false);
        lb_pin.setVisible(false);
        pin.setVisible(false);
        btn_pin.setVisible(false);
    }//GEN-LAST:event_radio_btn_renfeActionPerformed

    /**
     * Evento al seleccionar la opción de pago con tarjeta de crédito
     */
    private void radio_btn_creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_btn_creditoActionPerformed
        miControlador.resetTodo();
        lb_error4.setVisible(false);
        if(radio_btn_renfe.isSelected()){
            radio_btn_renfe.setSelected(false);
        }
        radio_btn_credito.setSelected(true);
        lb_tarjetacredito.setVisible(true);
        lb_mantener_credito.setVisible(true);
        lb_pin.setVisible(true);
        pin.setVisible(true);
        btn_pin.setVisible(true);
        lb_tarjetarenfe.setVisible(false);
        lb_mantener_renfe.setVisible(false);
    }//GEN-LAST:event_radio_btn_creditoActionPerformed

    /**
     * Evento al pulsar el botón de anterior del tercer paso
     */
    private void btn_ant_p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ant_p3ActionPerformed
        setVisible(0,1,0);
        setNoVisible(1,0,1);
    }//GEN-LAST:event_btn_ant_p3ActionPerformed

    /**
     * Evento al pulsar el botón de intercambio de estaciones
     */
    private void btn_intercambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_intercambioActionPerformed
        int origen = elegir_salida.getSelectedIndex();
        int destino = elegir_destino.getSelectedIndex();
        elegir_salida.setSelectedIndex(destino);
        elegir_destino.setSelectedIndex(origen);
    }//GEN-LAST:event_btn_intercambioActionPerformed

    /**
     * Evento al pulsar el botón de aceptar el PIN
     */
    private void btn_pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pinActionPerformed
        if(miControlador.comprobarPagoCredito(getPIN())){   //Se ha pagado con tarjeta de crédito y el PIN es correcto
            lb_error4.setVisible(false);
            pago_correcto.setVisible(true);
        }
        else{
            pin.setText("");
            lb_error4.setText("Error al procesar el pago");
            lb_error4.setVisible(true);
        }
    }//GEN-LAST:event_btn_pinActionPerformed
    
    /**
     * Evento al introducir el ratón sobre la tarjeta de crédito
     */
    private void lb_tarjetacreditoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_tarjetacreditoMouseEntered
        timer_tarjeta_credito.start();
    }//GEN-LAST:event_lb_tarjetacreditoMouseEntered

    /**
     * Evento al sacar el ratón de la tarjeta de crédito
     */
    private void lb_tarjetacreditoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_tarjetacreditoMouseExited
        timer_tarjeta_credito.stop();
    }//GEN-LAST:event_lb_tarjetacreditoMouseExited

    /**
     * Evento al introducir el ratón sobre la tarjeta de usuario de TCyL
     */
    private void lb_tarjetarenfeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_tarjetarenfeMouseEntered
        timer_tarjeta_renfe.start();
    }//GEN-LAST:event_lb_tarjetarenfeMouseEntered

    /**
     * Evento al sacar el ratón de la tarjeta de usuario de TCyL
     */
    private void lb_tarjetarenfeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_tarjetarenfeMouseExited
        timer_tarjeta_renfe.stop();
    }//GEN-LAST:event_lb_tarjetarenfeMouseExited

    /**
     * Evento al pulsar el botón de comprar nuevo billete
     */
    private void btn_billeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_billeteActionPerformed
        resetTodo();
        setVisible(1,0,0);
        setNoVisible(0,1,1);
        pago_correcto.dispose();
    }//GEN-LAST:event_btn_billeteActionPerformed

    /**
     * Evento al pulsar el botón de salir
     */
    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ant_p2;
    private javax.swing.JButton btn_ant_p3;
    private javax.swing.JButton btn_billete;
    private javax.swing.JButton btn_intercambio;
    private javax.swing.JButton btn_pin;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_sig_p1;
    private javax.swing.JButton btn_sig_p2;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JCheckBox check_box_bici;
    private javax.swing.JCheckBox check_box_mascota;
    private javax.swing.JCheckBox check_box_silla;
    private javax.swing.JComboBox<String> elegir_destino;
    private javax.swing.JComboBox<String> elegir_salida;
    private javax.swing.JPanel info1;
    private javax.swing.JPanel info2;
    private javax.swing.JPanel info3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_bicicleta;
    private javax.swing.JLabel lb_equipaje;
    private javax.swing.JLabel lb_error1;
    private javax.swing.JLabel lb_error2;
    private javax.swing.JLabel lb_error3;
    private javax.swing.JLabel lb_error4;
    private javax.swing.JLabel lb_mantener_credito;
    private javax.swing.JLabel lb_mantener_renfe;
    private javax.swing.JLabel lb_mascota;
    private javax.swing.JLabel lb_pago_aceptado;
    private javax.swing.JLabel lb_pin;
    private javax.swing.JLabel lb_silla;
    private javax.swing.JLabel lb_tarjetacredito;
    private javax.swing.JLabel lb_tarjetarenfe;
    private javax.swing.JList<String> lista_rutas_posibles;
    private javax.swing.JDialog pago_correcto;
    private javax.swing.JPasswordField pin;
    private javax.swing.JRadioButton radio_btn_credito;
    private javax.swing.JRadioButton radio_btn_renfe;
    private javax.swing.JLabel subtitulo1;
    private javax.swing.JLabel subtitulo2;
    private javax.swing.JLabel subtitulo3;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    // End of variables declaration//GEN-END:variables
}
