package uva.ipc.practica2.vista;

/**
 * Clase para la interfaz gráfica de la vista de menu principal
 * @author Fernando Carmona
 * @author Rodrigo Serna
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {

    private ControladorMenuPrincipal miControlador;
    
    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
        miControlador = new ControladorMenuPrincipal(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGlobal = new javax.swing.JPanel();
        pnlTexto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        pnlBtnSup = new javax.swing.JPanel();
        btnComprar = new javax.swing.JButton();
        btnTarjeta = new javax.swing.JButton();
        pnlBtnInf = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(233, 255, 255));

        panelGlobal.setBackground(new java.awt.Color(233, 255, 255));
        panelGlobal.setLayout(new java.awt.BorderLayout(15, 15));

        pnlTexto.setBackground(new java.awt.Color(233, 255, 255));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(94, 145, 136));
        jLabel1.setText("BIENVENIDO A TCYL");
        pnlTexto.add(jLabel1);

        panelGlobal.add(pnlTexto, java.awt.BorderLayout.PAGE_START);

        pnlBotones.setBackground(new java.awt.Color(233, 255, 255));
        pnlBotones.setLayout(new java.awt.GridLayout(2, 1));

        pnlBtnSup.setBackground(new java.awt.Color(233, 255, 255));
        pnlBtnSup.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 50));

        btnComprar.setBackground(new java.awt.Color(94, 145, 136));
        btnComprar.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar.setText("COMPRAR BILLETE");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        pnlBtnSup.add(btnComprar);

        btnTarjeta.setBackground(new java.awt.Color(94, 145, 136));
        btnTarjeta.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        btnTarjeta.setText("ACCESO CON TARJETA");
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });
        pnlBtnSup.add(btnTarjeta);

        pnlBotones.add(pnlBtnSup);

        pnlBtnInf.setBackground(new java.awt.Color(233, 255, 255));

        btnSalir.setBackground(new java.awt.Color(94, 145, 136));
        btnSalir.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnInfLayout = new javax.swing.GroupLayout(pnlBtnInf);
        pnlBtnInf.setLayout(pnlBtnInfLayout);
        pnlBtnInfLayout.setHorizontalGroup(
            pnlBtnInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(pnlBtnInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBtnInfLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSalir)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlBtnInfLayout.setVerticalGroup(
            pnlBtnInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
            .addGroup(pnlBtnInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBtnInfLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSalir)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlBotones.add(pnlBtnInf);

        panelGlobal.add(pnlBotones, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        miControlador.procesarComprar();
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
        miControlador.procesarTarjeta();
    }//GEN-LAST:event_btnTarjetaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        miControlador.procesarSalir();
    }//GEN-LAST:event_btnSalirActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelGlobal;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlBtnInf;
    private javax.swing.JPanel pnlBtnSup;
    private javax.swing.JPanel pnlTexto;
    // End of variables declaration//GEN-END:variables
}
