package uva.ipc.practica2.vista;

/**
 * Clase para la interfaz gráfica de la vista de recargar tarjeta
 * @author Fernando Carmona
 * @author Rodrigo Serna
 */
public class VistaRecargarTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form VistaRecargarTarjeta
     */
    public VistaRecargarTarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGlobal = new javax.swing.JPanel();
        pnlCentral = new javax.swing.JPanel();
        lbRecargar = new javax.swing.JLabel();
        pnlBilletes = new javax.swing.JPanel();
        btnBillete10 = new javax.swing.JToggleButton();
        btnBillete20 = new javax.swing.JToggleButton();
        btnBillete50 = new javax.swing.JToggleButton();
        pnlCabecera = new javax.swing.JPanel();
        lbSaldo = new javax.swing.JLabel();
        pnlPie = new javax.swing.JPanel();
        btnRecargar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(233, 255, 255));

        pnlGlobal.setBackground(new java.awt.Color(233, 255, 255));
        pnlGlobal.setLayout(new java.awt.BorderLayout(15, 15));

        pnlCentral.setBackground(new java.awt.Color(233, 255, 255));
        pnlCentral.setLayout(new java.awt.GridLayout(2, 1));

        lbRecargar.setForeground(new java.awt.Color(94, 145, 136));
        lbRecargar.setText("RECARGAR:");
        lbRecargar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pnlCentral.add(lbRecargar);

        pnlBilletes.setBackground(new java.awt.Color(233, 255, 255));

        btnBillete10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billete10.png"))); // NOI18N
        btnBillete10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillete10ActionPerformed(evt);
            }
        });
        pnlBilletes.add(btnBillete10);

        btnBillete20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billete20.jpg"))); // NOI18N
        pnlBilletes.add(btnBillete20);

        btnBillete50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billete50.png"))); // NOI18N
        pnlBilletes.add(btnBillete50);

        pnlCentral.add(pnlBilletes);

        pnlGlobal.add(pnlCentral, java.awt.BorderLayout.CENTER);

        pnlCabecera.setBackground(new java.awt.Color(233, 255, 255));

        lbSaldo.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lbSaldo.setForeground(new java.awt.Color(94, 145, 136));
        lbSaldo.setText("SALDO DE LA TARJETA: X€");

        javax.swing.GroupLayout pnlCabeceraLayout = new javax.swing.GroupLayout(pnlCabecera);
        pnlCabecera.setLayout(pnlCabeceraLayout);
        pnlCabeceraLayout.setHorizontalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
            .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCabeceraLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbSaldo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlCabeceraLayout.setVerticalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCabeceraLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbSaldo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlGlobal.add(pnlCabecera, java.awt.BorderLayout.PAGE_START);

        pnlPie.setBackground(new java.awt.Color(233, 255, 255));
        pnlPie.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        btnRecargar.setBackground(new java.awt.Color(94, 145, 136));
        btnRecargar.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnRecargar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecargar.setText("RECARGAR ESTA CANTIDAD");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        pnlPie.add(btnRecargar);

        btnVolver.setBackground(new java.awt.Color(94, 145, 136));
        btnVolver.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        pnlPie.add(btnVolver);

        pnlGlobal.add(pnlPie, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBillete10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillete10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBillete10ActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRecargarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRecargarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRecargarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRecargarTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRecargarTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBillete10;
    private javax.swing.JToggleButton btnBillete20;
    private javax.swing.JToggleButton btnBillete50;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lbRecargar;
    private javax.swing.JLabel lbSaldo;
    private javax.swing.JPanel pnlBilletes;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlGlobal;
    private javax.swing.JPanel pnlPie;
    // End of variables declaration//GEN-END:variables
}
